- soap-tck/README.md
- soap-tck/run-tck.sh
SOAP TCK is based on JT, e.g. not Arquillian.
This script downloads TCK, unpacks and prepares variables. The only place to edit is the directory of local Payara.
> add script to download and prepare SOAP TCK tests

- core-tck/pom.xml
- core-tck/src/test/resources/arquillian.xml
- pom.xml
Currently running into the following issue when running the core-profile tck 
fish.payara.arquillian.jersey.server.ContainerException: While Deploying Application: CustomJsonbSerializationIT --exit_code: FAILURE, message: Error occurred during deployment: Exception while deploying the app [CustomJsonbSerializationIT] : The lifecycle method [loadKeys] must not throw a checked exception. Related annotation information: annotation [@jakarta.annotation.PostConstruct()] on annotated element [private void ee.jakarta.tck.core.rest.jsonb.cdi.KeysProducer.loadKeys() throws java.lang.Exception] of type [METHOD]. Please see server.log for more details. [status: CLIENT_ERROR reason: Bad Request]
jakarta.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
SEVERE: While Deploying …
> FISH-6342 Add Core Profile TCK Runner

- batch-tck/README.md
- batch-tck/apitests/pom.xml
- batch-tck/apitests/src/test/resources/arquillian.xml
- batch-tck/apitests/src/test/resources/derby.ddl.jbatch-tck.sql
- batch-tck/pom.xml
- batch-tck/sigtests/pom.xml
- pom.xml
Adds a TCK runner for Batch.
It's based on the GlassFish runner, but quite heavily edited for use with Payara.
The Batch TCK makes use of Shrinkwrap Maven resolver, which is extremely annoying in that it ignores properties you define on the command line, it will **always** read the pom as-is - hence why `payara.version` is left purposefully blank and the README says to fill it in yourself.
> FISH-6448 Batch TCK Runner

- authentication-tck/old-tck-run.xml
- authentication-tck/pom-old-tck-run.xml
- authentication-tck/run-tck.sh
Activates the Old TCK Module in the authentication TCK.
Replaces the default pom with hard-coded GlassFish replaced by hard-coded Payara, replaces a number of "glassfish" variables with "payara", and also changes the GFAuthConfigFactory signature to the one used in Payara.
> FISH-6538 Activate Authentication Old-TCK

- rest-tck/pom.xml
[tck-download/jakarta-rest-tck](https://github.com/payara/jakartaee-10-tck-runners/tree/main/tck-download/jakarta-rest-tck) is using version 3.1.2 yet the rest-tck itself still using 3.1.1 which is not found in any repository
> FISH-6357 Upgrade rest-tck

- concurrent-tck/pom.xml
Payara succeeds Concurrency TCK 3.0.2 as a part of fix FISH-6556.
> FISH-6556 Upgrade Concurrency TCK to 3.0.2

- README.md
- concurrent-tck/README.md
- concurrent-tck/pom.xml
- concurrent-tck/src/test/resources/tck-suite-web.xml
- concurrent-tck/src/test/resources/tck-suite.xml
Adds a second tck-suite.xml with the expected excluded group - activated via the `web` profile.
> FISH-6646 Concurrency Web Profile

- authorization-tck/pom.xml
- pom.xml
1) Build is fixed, if the test fails, the whole build fails.
2) Adding setup of trustStore password (this was the reason, why the test failed).
How to test:
Checkout, run `JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 mvn clean verify -Dpayara.version=6.2023.3-SNAPSHOT`.
If running for a second run, manually remove the target directory.
> Fish 6406 fail maven if authorization tests fail

- servlet-tck/pom.xml
- websocket-tck/pom.xml
Add fail conditions when running Websocket and Servlet TCKs, so the test runs return as a failure instead of a success when at least one test fails
> FISH-6650 servlet tck success when fail

- .gitmodules
- cdi-tck/README.md
This is to upgrade to the latest changes added for the CDI-4.1 branch on the cditck-porting project and improve tck execution
> FISH-9109:upgrading cditck-porting reference to latest commit 

- websocket-tck/pom.xml
Reduce the sleep from 60 seconds to 5.
The block has a timeout of 60 seconds, so the sleep was 100% forcing the block to exit partway through: skipping configuration of jacoco (if set), the enabling of HTTP2 push, and turning off the domain.
> FISH-9185 Reduce Websocket Sleep

- cdi-langmodel-tck/pom.xml
Updating to the latest version of weld and payara arquillian to execute cdi lang tck
Manual testing
execution of cdi lang without any issue:
Environment:
ubuntu 20.04, azul jdk 21, maven 3.8.6
> FISH-9156: update of weld versions and dependencies

- pom.xml
- tck-download/jakarta-websocket-tck/pom.xml
- websocket-tck/README.md
- websocket-tck/pom.xml
This is to improve the websocket TCK execution without the need to use ant and just use maven configuration.
Manual testing executing TCK with the following results:
`
[INFO]
[INFO]
[ERROR] Errors:
[ERROR]   WebSocketSigTestIT.signatureTest:246->SigTest.signatureTest:260 »  SigTest.test1() failed!, diffs found
[INFO]
[ERROR] Tests run: 737, Failures: 0, Errors: 1, Skipped: 0
`
> Fish 9013 updating websocket tck configuration

- pom.xml
- websocket-tck/pom.xml
Fix for websocket signature test
For testing the local execution of tck is passing all tests including signature test:
`
[INFO]
[INFO]
[INFO] Tests run: 737, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.3.0:verify (payara-tests) @ websocket-tck-runner ---
[INFO] BUILD SUCCESS
`
something to take care regarding latest version of sigtest-maven-plugin was that the latest version is causing the following issue: 
`
Aug 27, 2024 11:11:58 PM com.sun.ts.tests.signaturetest.SigTestDriver runSignatureTest
INFO: ********** Status Report 'jakarta.websocket.server' **********
Aug 27, 2024 11:11:58 PM com.sun.ts.tests.signaturetest.SigTestDriver runSignatureTest
INFO: …
> FISH-9459: adding changes to pass websocket signature test

- batch-tck/apitests/pom.xml
- batch-tck/pom.xml
- batch-tck/sigtests/pom.xml
- pom.xml
Updates various dependencies for EE11 and JDK 21, and reintegrates with the main project - shrinkwrap resolver is still an issue, but Jenkins already performs a sed to replace the version for us.
Tested locally using `mvn clean verify -Ppayara-server-managed -pl . -pl batch-tck -pl batch-tck/apitests -pl batch-tck/sigtests`
> FISH-9019 Update EE11 Batch TCK Runner Config

- authorization-tck/README.md
- authorization-tck/payara-pom.xml
This profiles is for rerunning the TCK - it expects that the TCK has been run at least once using the default `payara-server-managed` profile to perform the usual setup.
This allows for easier debug of specific tests, as we won't be chaining runs via exec and instead running "directly".
Note that with how this is now, to utilise this profile you have to install some additional "common" bits from the TCK itself.
The general flow is:
* Run the TCK in the "normal" way: `mvn clean install -pl . -pl tck-download/ -pl tck-download/jakarta-authorization-tck/ -pl authorization-tck/ -Ppayara-server-managed,jakarta-staging`
* Move into the TCK for the rerun: `cd authorization-tck/target/authorization-tck-3.0.0/tck`
* Install the common TCK module (make sure you don't `clean`!): `mvn install …
> Add `payara-server-remote` Profile for Authorization

- concurrent-tck/pom.xml
- pom.xml
In the current version, security fails. This is fixed by https://github.com/payara/Payara/pull/6998
Then all tests pass.
> FISH-9468 Upgrade Concurrency TCK to 3.1.1

- inject-tck/build.sh
- inject-tck/get-dependencies.xml
Updates the Dependency Injection runner for EE11.
The porting package stuff which we were using to run against Payara itself (rather than just standalone weld) has been removed from the CDI TCK itself. I have introduced a pom which largely recreates what it does: downloads weld binaries so they can be added to the classpath.
> FISH-10040 Update DI TCK Runner and Submodule for EE11

- authentication-tck/README.md
- authentication-tck/payara-profiles.xml
Adjust the runner for the Epicyro integration done here: https://github.com/payara/Payara/pull/7068
Follow-up to https://github.com/payara/jakartaee-10-tck-runners/pull/118
> FISH-9002 Adjust EE11 Authentication Runner for Epicyro

- faces-tck/pom.xml
- faces-tck/pom.xml-tck-util
- faces-tck/run-tck.sh
How I tested:
1. You need Maven 3.9.6 (or newer), Java 21
1. Download the TCK in tck-download/jakarta-faces-tck (go there, run `mvn clean install`)
1. Compile latest Payara 7, don't use QuickBuild profile (test needs zip), use jakarta-staging, ! `mvn clean install -Pjakarta-staging -T 16 -DskipTests -Dmaven.test.skip -Djavadoc.skip=true -Dsource.skip=true`
From `/faces-tck`, run only the old part of the TCK:
```
~/programs/java/maven/apache-maven-3.9.6/bin/mvn -B clean install test verify -Dtck.mode=platform -Dmojarra.noupdate=true -Dpayara.version=7.2025.1.Alpha1-SNAPSHOT -Dfaces.version=4.1.1 -Dmaven.exec.skipping="-pl :old-faces-tck-parent,:old-tck-build,:old-tck-run"
```
It takes more than 4 hours! The total number of tests is 5391. I suggest monitoring by storing the output to a file …
> FISH-10299 Faces old-tests

- pom.xml
this is to fix tck failures from CDI caused by introducing Krazo MVC on the server. With this fix now the TCK is passing with success:
> FISH-10295: upgrading submodule to get latest changes from EE10 branch

- tags-tck/pom.xml
- tags-tck/sql/derby/derby.ddl.jstl.sql
- tck-download/jakarta-tags-tck/pom.xml
```
[INFO]
[INFO] Tests run: 541, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- antrun:3.1.0:run (stop-database) @ tags-tck-runner ---
[INFO] Executing tasks
[INFO]      [exec] Tue Jan 14 12:47:59 GMT 2025 : Apache Derby Network Server - 10.17.1.0 - (1913217) shutdown
[INFO] Executed tasks
[INFO]
[INFO] --- failsafe:3.3.0:verify (tests) @ tags-tck-runner ---
[INFO] Reactor Summary for tck 1.0-SNAPSHOT:
[INFO]
[INFO] tck ................................................ SUCCESS [  3.433 s]
[INFO] TCK: tags .......................................... SUCCESS [01:23 min]
[INFO] BUILD SUCCESS
[INFO] …
```
> FISH-9628 Update tags tck

- servlet-tck/pom.xml
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- failsafe:3.3.0:verify (verify) @ servlet-tck-runner ---
[INFO] Reactor Summary for tck 1.0-SNAPSHOT:
[INFO]
[INFO] tck ................................................ SUCCESS [  3.687 s]
[INFO] TCK: Servlet ....................................... SUCCESS [ 22.513 s]
[INFO] BUILD SUCCESS
[INFO] Total time:  26.428 s
[INFO] Finished at: 2025-01-14T13:50:01Z
[INFO]
[INFO] …
> FISH-10242 Fix client cert servlet tests

- security-tck/old-tck-run-payara.xml
- security-tck/payara-profile.xml
Upgrading version for derby to start database
before change the issues reported on logs were:
`
[INFO]      [exec] is.derby.running:
[INFO]      [exec]      [echo] *** There was a problem connecting to DB at jdbc:derby://localhost:1527/derbyDB;create=true
[INFO]      [exec]      [echo] Output:java.sql.SQLNonTransientConnectionException: A network protocol error was encountered and the connection has been terminated: A protocol error (Data Stream Syntax Error) was detected.  Reason: 0x1. Perhaps this is an attempt to open a plaintext connection to an SSL enabled server.
[INFO]      [exec]      [echo] Derby was NOT started successfully
`
and 
`
[WARNING]      [echo] Caused by: javax.naming.NamingException: jdbc/securityAPIDB
[WARNING]      [echo] 	at …
> FISH-10183: upgrading versions to start derby database used for old tck

- messaging-platform-tck/jakartaeetck/logging.properties
- messaging-platform-tck/pom.xml
- messaging-platform-tck/src/test/resources/appclient-arquillian.xml
- pom.xml
Updated dependencies, classpath and certificate type
Blocked by https://github.com/payara/Payara/pull/7204
I am aware of some failing tests due to issues in the TCK itself: https://github.com/jakartaee/platform-tck/issues/1495#issuecomment-2671433733
Run is pending... https://jenkins.payara.fish/job/FISH-10460-Dev/4/
> FISH-10460 Fix Messaging Appclient TCK

- security-tck/payara-profile.xml
- security-tck/run-tck.sh
This change makes it possible no run modules  app-openid2 and app-openid3 without errors regarding certificates and truststores.
> Fish 10181 fix html unit cce

- cdi-tck/pom.xml
While running the CDI TCK and encountering test failures, the Maven process previously reported a build success without taking the test results into account. This PR fixes the issue by adding an Ant step that parses the test result file and looks for failures.
> FISH-10753: fixed cdi reporting

- authorization-tck/summary-tck.sh
This PR just adds a bash script for collecting all of the failsafe reports into one.
> FISH-10773: fixed Authorization TCK test reporting

- jsonb-platform-tck/pom.xml
- jsonp-platform-tck/pom.xml
Caused issues when running in Jenkins due to maven picking up the wrong commons codec version provided transitively 
https://jenkins.payara.fish/blue/organizations/jenkins/JakartaEE-11-TCK/detail/JakartaEE-11-TCK/174/pipeline/
> Fix commons codec issue

- assembly-platform-tck/pom.xml
- assembly-platform-tck/src/test/resources/appclient-arquillian.xml
This will fix the remaining failing tests in the assembly-platform tck regarding an alternative deployment descriptor.
This requires jakarta.tck.platform.version=11.0.1 - but will not update the pom due to issues in other tcks.
To run 
mvn clean verify -pl . -pl assembly-platform-tck -Ppayara-server-managed -Dit.test=Client#testAppClient -Djakarta.tck.platform.version=11.0.1
https://github.com/payara/EngineeringJenkinsjobs/pull/281
> FISH-11201 Update appclient-arquillian

- mail-platform-tck/pom.xml
Resyncs some config with the Platform TCK WRT to which libraries are required.
Also includes some misc little fixes to the runner itself (e.g. `skipConfig` instead of `skipTests`).
Tested here: https://jenkins.payara.fish/blue/organizations/jenkins/JakartaEE-11-TCK/detail/JakartaEE-11-TCK/227/pipeline
Missing server log collection will be addressed in another PR
> FISH-10840 Fix Mail TCK 
