concurrent-tck/src/test/resources/tck-suite.xml

Add information about challenges recorded in concurrency.

add tck challenges for concurrency

---

.gitignore
soap-tck/README.md
soap-tck/run-tck-setup.sh-template
soap-tck/run-tck.sh
xml-ws-tck/README.md
xml-ws-tck/prepare-server-password
xml-ws-tck/run-tck-setup.sh-template
xml-ws-tck/run-tck.sh

Add TCK Runner for XML WS by simple script.
Improve SOAP runner in the same way.

Add TCK Runner for XML WS

---

authentication-tck/run-tck.sh
rest-tck/pom.xml
tck-download/jakarta-faces-tck/pom.xml
tck-download/jakarta-rest-tck/pom.xml

Signed-off-by: Andrew Pielage <andrew.pielage@payara.fish>

Update TCKs to latest

---

batch-tck/apitests/pom.xml

Required for full certification

FISH-6448 Run suite in ejb and web contexts

---

security-tck/old-tck-payara.xml
security-tck/old-tck-run-payara.xml
security-tck/payara-profile.xml
security-tck/run-tck.sh

A bit scrappy, but worked locally - and retains the ability to test against GlassFish if desired.

FISH-6527 Run Security - Old TCK

---

jsonp-tck/pom.xml

Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>

FISH-6539 Pluggability TCK

---

batch-tck/pom.xml

Signed-off-by: Andrew Pielage <andrew.pielage@payara.fish>

FISH-6548 Download Batch from Central, not Staging

---

concurrent-tck/pom.xml

https://github.com/payara/jakartaee-10-tck-runners/pull/38
This but use 3.0.1

FISH-6549 Alternative - Use 3.0.1

---

inject-tck/build.sh
jsonp-tck/pom.xml

inject 2.0.2, verified by Jenkins build JakartaEE-10-TCK/205
jsonp 2.1.1, verified by Jenkins build JakartaEE-10-TCK/204

FISH-6511 Upgrade inject and jsonp TCKs to the Latest Versions

---

summarizer/README.md
summarizer/src/main/java/fish/payara/internal/tcksummarizer/Main.java
summarizer/src/main/java/fish/payara/internal/tcksummarizer/TxtParser.java
summarizer/src/main/java/fish/payara/internal/tcksummarizer/XmlParser.java
summarizer/src/test/java/fish/payara/internal/tcksummarizer/SmokeTest.java

Signed-off-by: Simon Laden <simon.laden@payara.fish>
Fixed few bugs + new format "collection", merging summary files into one.
This is porting the changes brought by FISH-6613 to the MP TCK runner (see https://github.com/payara/MicroProfile-TCK-Runners/pull/194 )

FISH-6613 - add format collection + small fixes

---

annotations-tck/pom.xml
pom.xml
tck-download/jakarta-annotations-tck/pom.xml
tck-download/pom.xml

Also removes some duplicate config by moving it into the parent pom.
Also adds enforcer plugin to ensure we're using Java 21.

FISH-8984 Add Runner for Annotations TCK

---

jsonp-tck/glassfish-runner-pluggability/pom.xml
jsonp-tck/glassfish-runner/pom.xml
jsonp-tck/payara-runner/pom.xml
jsonp-tck/pom.xml
pom.xml

[INFO] Reactor Summary for Jakarta JSON Processing TCK Runner 1.0-SNAPSHOT:
[INFO]
[INFO] Jakarta JSON Processing TCK Runner ................. SUCCESS [  0.070 s]
[INFO] Jakarta JSON Processing TCK Runner - Payara Runner . SUCCESS [ 29.583 s]
[INFO] Jakarta JSON Processing TCK Runner - GlassFish Runner SUCCESS [ 14.325 s]
[INFO] Jakarta JSON Processing TCK Runner - GlassFish Pluggability Runner SUCCESS [  2.980 s]
[INFO] BUILD SUCCESS
[INFO] ----------------------------------------------------------------------

Fish 8990 run jsonp tck

---

expression-language-tck/pom.xml

Allows the TCK to pass on Windows.

FISH-8987 Adjust File and Path Separators

---

activation-tck/pom.xml
pom.xml
tck-download/jakarta-activation-tck/pom.xml
tck-download/pom.xml

The build finishes with success, but it seems that no ant tests are found

Fish 8992 run activation tck

---

cdi-langmodel-tck/pom.xml
pom.xml

Some assorted improvements implemented while testing Lang Model locally on Windows

Assorted Improvements

---

cdi-langmodel-tck/pom.xml
cdi-tck/pom.xml
core-tck/pom.xml
inject-tck/pom.xml
jsonb-tck/README.md
jsonb-tck/pom.xml
jsonp-tck/pom.xml
pom.xml
rest-tck/payara-server-remote-tests/pom.xml
rest-tck/pom.xml
summarizer/pom.xml

Built on top of https://github.com/payara/jakartaee-10-tck-runners/pull/65
Also includes some cleanup of redundant properties.

FISH-8995 Update JSON-B TCK for Java 21 and EE11

---

tck-download/jakarta-tags-tck/pom.xml

FISH-9017 Use 3.0.1 Tags tck

---

authorization-tck/payara-pom.xml
authorization-tck/pom.xml
cdi-langmodel-tck/pom.xml
rest-tck/se-tests/pom.xml

Arquillian being updated to 1.9.1 changes a dependency name.

Update Dependencies for Arquillian 1.9.1

---

pages-tck/README.MD
pages-tck/pom.xml
pom.xml
tck-download/jakarta-pages-tck/assembly/sources.xml
tck-download/jakarta-pages-tck/pom.xml

Enabling pages TCK execution using maven configuration. Right now on local I have the following results:
this results are equivalent from Glassfish:

Fish 9008 run pages tck

---

rest-tck/payara-server-remote-tests/pom.xml

FISH-9592 Add missing roles

---

security-tck/summary-tck.sh

FISH-10057: added custom failsafe xml parser for security tck

---

pom.xml
servlet-tck/src/test/arquillian.xml

- updated payara arquillian connector
- enable https option

FISH-10208 update to use new arquillian and configure ssl tests

---

authentication-tck/README.md
authentication-tck/replaceScript.ps1
authentication-tck/replaceScript.sh

Dependent on https://github.com/payara/Payara/pull/7166
We used the wrong file name
[INFO] Reactor Summary:
[INFO]
[INFO] Jakarta Authentication TCK - common 1.0-SNAPSHOT ... SUCCESS [  0.922 s]
[INFO] Jakarta Authentication TCK - main 3.1.0 ............ SUCCESS [ 14.583 s]
[INFO] Jakarta Authentication TCK - basic-authentication 3.1.0 SUCCESS [ 11.193 s]
[INFO] Jakarta Authentication TCK - custom principal 3.1.0  SUCCESS [ 10.560 s]
[INFO] Jakarta Authentication TCK - programmatic-authentication 3.1.0 SUCCESS [ 10.661 s]
[INFO] Jakarta Authentication TCK - lifecycle 3.1.0 ....... SUCCESS [ 10.516 s]
[INFO] Jakarta Authentication TCK - wrapping 3.1.0 ........ SUCCESS [ 10.504 s]
[INFO] Jakarta Authentication …

FISH-10225 Fix Failures in Authentication TCK: SPI SOAP

---

annotations-tck/pom.xml
data-tck/README.md
data-tck/pom.xml
expression-language-tck/pom.xml
jsonp-tck/glassfish-runner-pluggability/pom.xml
jsonp-tck/glassfish-runner/pom.xml
jsonp-tck/payara-runner/pom.xml
mail-platform-tck/pom.xml
pages-tck/pom.xml
pom.xml
rest-tck/payara-server-remote-tests/pom.xml
servlet-tck/pom.xml
tck-download/jakarta-data-tck/pom.xml
tck-download/pom.xml
websocket-tck/pom.xml

Also includes some supplementary component upgrades and fixes

FISH-9610 Add Data TCK Runner

---

security-tck/summary-tck.sh

Syncs the summarizer script from the `main` branch

FISH-9144 Add Security TCK Summarizer

---

assembly-platform-tck/pom.xml
connector-platform-tck/old-pom.xml
connector-platform-tck/pom.xml
pom.xml

FISH-11139 Use 11.0.1-M4

---

integration-platform-tck/pom.xml

[INFO]
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0

FISH-11186 Add trustStore password to integration platform tck

---

jdbc-platform-tck/pom.xml

https://jenkins.payara.fish/view/All/job/FISH-11295-Development/6/
https://jenkins.payara.fish/view/All/job/FISH-11295-Development/7/

FISH-11295 Move appclient to seperate profile
